package biomes

var (
	biomeToID = map[string]int32{
		"minecraft:the_void":                 0,
		"minecraft:plains":                   1,
		"minecraft:sunflower_plains":         2,
		"minecraft:snowy_plains":             3,
		"minecraft:ice_spikes":               4,
		"minecraft:desert":                   5,
		"minecraft:swamp":                    6,
		"minecraft:mangrove_swamp":           7,
		"minecraft:forest":                   8,
		"minecraft:flower_forest":            9,
		"minecraft:birch_forest":             10,
		"minecraft:dark_forest":              11,
		"minecraft:old_growth_birch_forest":  12,
		"minecraft:old_growth_pine_taiga":    13,
		"minecraft:old_growth_spruce_taiga":  14,
		"minecraft:taiga":                    15,
		"minecraft:snowy_taiga":              16,
		"minecraft:savanna":                  17,
		"minecraft:savanna_plateau":          18,
		"minecraft:windswept_hills":          19,
		"minecraft:windswept_gravelly_hills": 20,
		"minecraft:windswept_forest":         21,
		"minecraft:windswept_savanna":        22,
		"minecraft:jungle":                   23,
		"minecraft:sparse_jungle":            24,
		"minecraft:bamboo_jungle":            25,
		"minecraft:badlands":                 26,
		"minecraft:eroded_badlands":          27,
		"minecraft:wooded_badlands":          28,
		"minecraft:meadow":                   29,
		"minecraft:grove":                    30,
		"minecraft:snowy_slopes":             31,
		"minecraft:frozen_peaks":             32,
		"minecraft:jagged_peaks":             33,
		"minecraft:stony_peaks":              34,
		"minecraft:river":                    35,
		"minecraft:frozen_river":             36,
		"minecraft:beach":                    37,
		"minecraft:snowy_beach":              38,
		"minecraft:stony_shore":              39,
		"minecraft:warm_ocean":               40,
		"minecraft:lukewarm_ocean":           41,
		"minecraft:deep_lukewarm_ocean":      42,
		"minecraft:ocean":                    43,
		"minecraft:deep_ocean":               44,
		"minecraft:cold_ocean":               45,
		"minecraft:deep_cold_ocean":          46,
		"minecraft:frozen_ocean":             47,
		"minecraft:deep_frozen_ocean":        48,
		"minecraft:mushroom_fields":          49,
		"minecraft:dripstone_caves":          50,
		"minecraft:lush_caves":               51,
		"minecraft:deep_dark":                52,
		"minecraft:nether_wastes":            53,
		"minecraft:warped_forest":            54,
		"minecraft:crimson_forest":           55,
		"minecraft:soul_sand_valley":         56,
		"minecraft:basalt_deltas":            57,
		"minecraft:the_end":                  58,
		"minecraft:end_highlands":            59,
		"minecraft:end_midlands":             60,
		"minecraft:small_end_islands":        61,
		"minecraft:end_barrens":              62,
	}
	idToBiome = map[int32]string{
		0:  "minecraft:the_void",
		1:  "minecraft:plains",
		2:  "minecraft:sunflower_plains",
		3:  "minecraft:snowy_plains",
		4:  "minecraft:ice_spikes",
		5:  "minecraft:desert",
		6:  "minecraft:swamp",
		7:  "minecraft:mangrove_swamp",
		8:  "minecraft:forest",
		9:  "minecraft:flower_forest",
		10: "minecraft:birch_forest",
		11: "minecraft:dark_forest",
		12: "minecraft:old_growth_birch_forest",
		13: "minecraft:old_growth_pine_taiga",
		14: "minecraft:old_growth_spruce_taiga",
		15: "minecraft:taiga",
		16: "minecraft:snowy_taiga",
		17: "minecraft:savanna",
		18: "minecraft:savanna_plateau",
		19: "minecraft:windswept_hills",
		20: "minecraft:windswept_gravelly_hills",
		21: "minecraft:windswept_forest",
		22: "minecraft:windswept_savanna",
		23: "minecraft:jungle",
		24: "minecraft:sparse_jungle",
		25: "minecraft:bamboo_jungle",
		26: "minecraft:badlands",
		27: "minecraft:eroded_badlands",
		28: "minecraft:wooded_badlands",
		29: "minecraft:meadow",
		30: "minecraft:grove",
		31: "minecraft:snowy_slopes",
		32: "minecraft:frozen_peaks",
		33: "minecraft:jagged_peaks",
		34: "minecraft:stony_peaks",
		35: "minecraft:river",
		36: "minecraft:frozen_river",
		37: "minecraft:beach",
		38: "minecraft:snowy_beach",
		39: "minecraft:stony_shore",
		40: "minecraft:warm_ocean",
		41: "minecraft:lukewarm_ocean",
		42: "minecraft:deep_lukewarm_ocean",
		43: "minecraft:ocean",
		44: "minecraft:deep_ocean",
		45: "minecraft:cold_ocean",
		46: "minecraft:deep_cold_ocean",
		47: "minecraft:frozen_ocean",
		48: "minecraft:deep_frozen_ocean",
		49: "minecraft:mushroom_fields",
		50: "minecraft:dripstone_caves",
		51: "minecraft:lush_caves",
		52: "minecraft:deep_dark",
		53: "minecraft:nether_wastes",
		54: "minecraft:warped_forest",
		55: "minecraft:crimson_forest",
		56: "minecraft:soul_sand_valley",
		57: "minecraft:basalt_deltas",
		58: "minecraft:the_end",
		59: "minecraft:end_highlands",
		60: "minecraft:end_midlands",
		61: "minecraft:small_end_islands",
		62: "minecraft:end_barrens",
	}
)

// IDToJavaName returns the name of the biome with the given ID.
func IDToJavaName(id int32) (string, bool) {
	name, ok := idToBiome[id]
	return name, ok
}

// JavaNameToID returns the ID of the biome with the given name.
func JavaNameToID(name string) (int32, bool) {
	id, ok := biomeToID[name]
	return id, ok
}
